export function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-[#FFB800] font-mono px-4 py-12">
      <div className="max-w-3xl mx-auto">
        <a href="/" className="text-[10px] uppercase tracking-widest text-[#FFB800]/40 hover:text-[#FFB800] transition-colors mb-8 inline-block">
          ← BACK TO APP
        </a>

        <div className="text-[10px] text-[#FFB800]/30 uppercase tracking-widest mb-2">// LEGAL</div>
        <h1 className="text-3xl font-black uppercase tracking-tight mb-2">TERMS OF SERVICE</h1>
        <p className="text-[10px] text-[#FFB800]/30 uppercase tracking-widest mb-12">
          LAST UPDATED: JUNE 2026 // TERMINAL_V2.0.0
        </p>

        <div className="space-y-10 text-sm text-[#FFB800]/70 leading-relaxed">
          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              1. ACCEPTANCE OF TERMS
            </h2>
            <p>
              By accessing or using Proof of Alpha ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the Service. These terms apply to all users,
              including visitors, registered users, and anyone who mints a Soulbound Token through the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              2. SERVICE DESCRIPTION
            </h2>
            <p className="mb-3">
              Proof of Alpha is an on-chain credential tool that allows users to:
            </p>
            <ul className="list-none space-y-2 text-[#FFB800]/50 pl-4">
              <li className="before:content-['//'] before:mr-2 before:text-[#FFB800]/30">Submit an EVM transaction hash for AI-powered forensic analysis</li>
              <li className="before:content-['//'] before:mr-2 before:text-[#FFB800]/30">Receive an Alpha Score (1–100) generated by an AI model</li>
              <li className="before:content-['//'] before:mr-2 before:text-[#FFB800]/30">Mint a Soulbound Token (SBT) on the Celo Mainnet representing that score</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              3. NOT FINANCIAL ADVICE
            </h2>
            <p>
              All analysis generated by Proof of Alpha is for informational and credentialing purposes only.
              Alpha Scores and forensic reports do not constitute financial advice, investment recommendations,
              or assessments of asset value. Users are solely responsible for their own investment decisions.
              Past on-chain activity does not guarantee future results.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              4. SOULBOUND TOKENS — IRREVERSIBILITY
            </h2>
            <p>
              Minting a Soulbound Token (SBT) is a permanent, irreversible on-chain action.
              Once minted, the SBT cannot be transferred, sold, burned, or removed from your wallet by Proof of Alpha
              or any third party. By initiating a mint transaction, you acknowledge and accept this irreversibility.
              You are solely responsible for confirming the transaction details before submission.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              5. AI ANALYSIS ACCURACY
            </h2>
            <p>
              Alpha Scores are generated by a third-party AI model (Groq / LLaMA 3.3 70B) based on publicly
              available on-chain data. Proof of Alpha makes no guarantee as to the accuracy, completeness, or
              fitness for any particular purpose of AI-generated analysis. Scores may vary and are not auditable
              by the user. The Service is provided "as is" without warranty of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              6. USER RESPONSIBILITIES
            </h2>
            <p className="mb-3">By using the Service, you represent and warrant that:</p>
            <ul className="list-none space-y-2 text-[#FFB800]/50 pl-4">
              <li className="before:content-['//'] before:mr-2 before:text-[#FFB800]/30">You are at least 18 years of age</li>
              <li className="before:content-['//'] before:mr-2 before:text-[#FFB800]/30">You have the right and authority to submit any transaction hash you analyze</li>
              <li className="before:content-['//'] before:mr-2 before:text-[#FFB800]/30">You are solely responsible for all gas fees and on-chain costs incurred</li>
              <li className="before:content-['//'] before:mr-2 before:text-[#FFB800]/30">You will not use the Service for any illegal purpose or in violation of any applicable law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              7. SERVICE AVAILABILITY AND MODIFICATIONS
            </h2>
            <p>
              Proof of Alpha reserves the right to modify, suspend, or discontinue the Service at any time without
              prior notice. We may also update these Terms of Service at any time. Continued use of the Service
              after changes are posted constitutes your acceptance of the revised terms. The smart contract
              deployed on Celo Mainnet operates independently and cannot be modified by us.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              8. LIMITATION OF LIABILITY
            </h2>
            <p>
              To the maximum extent permitted by applicable law, Proof of Alpha and its operators shall not be
              liable for any indirect, incidental, special, consequential, or punitive damages, including but not
              limited to loss of funds, loss of data, or any other damages arising out of or in connection with
              your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              9. GOVERNING LAW
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable international law.
              Any disputes arising under these Terms shall be resolved through good-faith negotiation first,
              followed by binding arbitration if necessary.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-black uppercase tracking-widest text-[#FFB800] mb-3 border-b border-[#FFB800]/20 pb-2">
              10. CONTACT
            </h2>
            <p>
              For questions or concerns regarding these Terms, contact us at:{' '}
              <a href="mailto:support@proofofal.pha" className="text-[#FFB800] hover:underline">
                support@proofofal.pha
              </a>
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-[#FFB800]/20 text-center text-[10px] text-white/20 uppercase tracking-widest">
          © 2026 PROOF OF ALPHA // TERMINAL_V2.0.0
        </div>
      </div>
    </div>
  );
}
